// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Classes;

#nullable disable

namespace TaskBoard.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231109092914_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "9fe07867-e47b-411c-a61d-c1e113df3795",
                            Login = "admin",
                            Password = "1",
                            Role = 0
                        },
                        new
                        {
                            Id = "2c1e7148-85bd-4c71-9edf-cfb972ee0903",
                            Login = "manager",
                            Password = "2",
                            Role = 1
                        },
                        new
                        {
                            Id = "09fbfda8-f74e-4e0b-9f9c-02e803d955c2",
                            Login = "user1",
                            Password = "3",
                            Role = 2
                        },
                        new
                        {
                            Id = "01eb55b7-4828-41e6-9130-7e308f64f152",
                            Login = "user2",
                            Password = "3",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
